# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      uses: apple/setup-swift@v1
      with:
        swift-version: 5.8
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
